spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviedb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  file:
    path: .
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics